In [0]:
from google.colab import drive

In [0]:
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
!ls "gdrive/My Drive/Colab Notebooks"

Churn_Modelling.csv  Untitled0.ipynb


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: agg


In [0]:
data= pd.read_csv("gdrive/My Drive/Colab Notebooks/Churn_Modelling.csv")

In [0]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [0]:
pd.plotting.scatter_matrix(data,figsize=(10,10));

In [0]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [0]:
data.index

RangeIndex(start=0, stop=10000, step=1)

In [0]:
data.values

array([[1, 15634602, 'Hargrave', ..., 1, 101348.88, 1],
       [2, 15647311, 'Hill', ..., 1, 112542.58, 0],
       [3, 15619304, 'Onio', ..., 0, 113931.57, 1],
       ...,
       [9998, 15584532, 'Liu', ..., 1, 42085.58, 1],
       [9999, 15682355, 'Sabbatini', ..., 0, 92888.52, 1],
       [10000, 15628319, 'Walker', ..., 0, 38190.78, 0]], dtype=object)

In [0]:
df = data

In [0]:
# here we give same useful pandas commands to understand the data
print("______The first 5 rows are______")
print(df.head(5))

# If it is too long, use instead
print(df.head(5).T)

print("______The last 5 rows are______")
print(df.tail(5))

# Here just put the command inside a print
df.columns
df.index
df.shape


______The first 5 rows are______
   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]
                        0         1         2         3         4
RowNumber               1         2         3         4         5
CustomerId       15634602  15647311  15619304  15701354  15737888
Surname          Hargrave      Hill      Onio      Boni  Mitchell
CreditScore           619       608       502       699       850
Geography          France     Spain    France    France     Spain
Gender             Female    Female    Female    Female    Female
Age     

(10000, 14)

In [0]:
X = df.iloc[:,3:13].values

In [0]:
y = df.iloc[:,13].values

In [0]:
from sklearn.preprocessing import LabelEncoder

label_encode_geography = LabelEncoder() 
label_encode_gender = LabelEncoder()


X[:,1] = label_encode_geography.fit_transform(X[:,1])
X[:,2] = label_encode_gender.fit_transform(X[:,2])

In [0]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
X = X[:,1:]

In [0]:
# Now, we split our data into training data and testing data
# Here we use the train test split technic

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)


# Feature Scaling using the mean and the standard deviation
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [0]:
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression()
model2.fit(X_train, y_train)
y_pred = model2.predict(X_test)
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test, y_pred)
cm2

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([[1543,   64],
       [ 314,   79]])

In [0]:
from sklearn.neighbors import KNeighborsClassifier
model3 = KNeighborsClassifier(n_neighbors=5)
model3.fit(X_train, y_train)
y_pred = model3.predict(X_test)
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y_test, y_pred)
cm3

array([[1514,   93],
       [ 247,  146]])

In [0]:
from sklearn.ensemble import RandomForestClassifier
model4 = RandomForestClassifier()
model4.fit(X_train, y_train)
y_pred = model4.predict(X_test)
from sklearn.metrics import confusion_matrix
cm4 = confusion_matrix(y_test, y_pred)
cm4

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([[1542,   65],
       [ 222,  171]])

In [0]:
%tensorflow_version 1.x

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
# Initialization of Sequential a linear stack of layers.
classifier = Sequential()

# An artificial neural neutworks contains an input layer
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6,
                     init = 'uniform',
                     activation = 'relu',
                     input_dim = 11)
                )



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [0]:
# Adding of the second hidden layer
classifier.add(Dense(output_dim = 6,
                     init = 'uniform',
                     activation = 'relu')
                )

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
# Adding of the third hidden layer
classifier.add(Dense(output_dim = 6,
                     init = 'uniform',
                     activation = 'relu')
                )

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
# Adding the output layer
classifier.add(Dense(output_dim = 1,
                     init = 'uniform',
                     activation = 'sigmoid')
                )

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
# Compiling the ANN
classifier.compile(optimizer='adam',
                   loss='binary_crossentropy',
                   metrics = ['accuracy']
                   )

In [0]:
classifier.fit(X_train, y_train, batch_size=10, nb_epoch=100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.





Epoch 1/100





8000/8000 [==============================] - 2s 235us/step - loss: 0.4805 - acc: 0.7945
Epoch 2/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4294 - acc: 0.7945
Epoch 3/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.4222 - acc: 0.8160
Epoch 4/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.4189 - acc: 0.8276
Epoch 5/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4172 - acc: 0.8310
Epoch 6/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.4145 - acc: 0.8334
Epoch 7/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4141 - acc: 0.8341
Epoch 8/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4129 - acc: 0.8329
Epoch 9/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4113 - acc: 0.8332
Epoch 10/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4112 - acc

In [0]:
y_pred = classifier.predict(X_test)

# Convert y_pred from probabilities to True or False
threshold = 0.5
y_pred = (y_pred > threshold)

In [0]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_pred)


In [0]:
cm1

array([[1555,   52],
       [ 260,  133]])